### PR TITLE
Mouse mode for pane management

### PR DESCRIPTION
**Pull request by Towerthousand**

### CODE REVIEW

**Comment by Towerthousand** [comment]
Yo this is dope.

**Comment by mvdan** [comment]
Commit squashing is for sissies.

**Comment by Towerthousand** [comment]
I did all of this on the github UI, too lazy to actually clone & squash shit. Too bad.

**Comment by Towerthousand** [comment]
OKAY WHATEVER

**Comment by dasilvacontin** [comment]
`mouse-resize-pane` is nice, but it leaves me wishing I could do it faster using the keyboard. `mouse-select-pane` is super nice if you want to scroll a pane but it's not selected.

LGTM, thanks for the addition. Looking forward to using tmux while I eat or something :)

**Pull request merged**
